name: borderless
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.1.0
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  pay: ^1.1.2
  bloc: ^8.1.3
  provider: ^6.0.5
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  auto_size_text: ^3.0.0
  webview_flutter: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  image: ^4.0.17

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/logo.png
    - assets/images/banner.png
    - assets/images/handbag.png
    - assets/images/watch.png
    - assets/images/headphones1.png
    - assets/images/headphones2.png
    - assets/images/headphones3.png
    - assets/images/headphones4.png
    - assets/images/headphones5.png
    - assets/images/headphones6.png
    - assets/images/watch1.png
    - assets/images/watch2.png
    - assets/images/watch3.png
    - assets/images/nike_shoes.png
    - assets/images/glasses.png
    - assets/images/empty_orders.png
    - assets/images/empty_cart.png
    - assets/images/empty_wishlist.png
    - assets/images/onboarding1.png
    - assets/images/onboarding2.png
    - assets/images/onboarding3.png
    - assets/images/apple-watch-series8.png
    - assets/images/paypal.png
    - assets/images/pk_flag.png
    - assets/images/order_success.png
    - assets/images/lock_success.png
<<<<<<< HEAD
    - assets/images/smartwatch.png
    - assets/images/backpack.png
    - assets/images/earbuds.png
    - assets/images/profile_image.png
=======
    - assets/images/headphone1.png
    - assets/images/smartwatch.png
    - assets/images/coffee_table.png
    - assets/images/tool_set.png
    - assets/images/vase.png
    - assets/images/subcategories/
    - assets/images/subcategories/laptops.png
    - assets/images/subcategories/mobile_phones.png
    - assets/images/subcategories/headphones.png
    - assets/images/subcategories/smart_watches.png
    - assets/images/subcategories/mobile_cases.png
    - assets/images/subcategories/monitors.png
    - assets/images/subcategories/mens_clothing.png
    - assets/images/subcategories/womens_clothing.png
    - assets/images/subcategories/kids_clothing.png
    - assets/images/subcategories/shoes.png
    - assets/images/subcategories/accessories.png
    - assets/images/subcategories/jewelry.png
    - assets/images/subcategories/living_room.png
    - assets/images/subcategories/bedroom.png
    - assets/images/subcategories/dining_room.png
    - assets/images/subcategories/office.png
    - assets/images/subcategories/outdoor.png
    - assets/images/subcategories/storage.png
    - assets/images/subcategories/machinery.png
    - assets/images/subcategories/tools.png
    - assets/images/subcategories/safety_equipment.png
    - assets/images/subcategories/industrial_supplies.png
    - assets/images/subcategories/workwear.png
    - assets/images/subcategories/maintenance.png
    - assets/images/subcategories/wall_art.png
    - assets/images/subcategories/lighting.png
    - assets/images/subcategories/rugs.png
    - assets/images/subcategories/cushions.png
    - assets/images/subcategories/curtains.png
    - assets/images/subcategories/decorative_items.png
    - assets/images/subcategories/building_materials.png
    - assets/images/subcategories/plumbing.png
    - assets/images/subcategories/electrical.png
    - assets/images/subcategories/concrete.png
    - assets/images/subcategories/roofing.png
    - assets/images/subcategories/insulation.png
    - assets/icons/
    - assets/icons/electronics_tv.png
    - assets/icons/electrical.png
    - assets/icons/filter.svg
    - assets/icons/search.svg
>>>>>>> b0f257b (Initial commit)
    - assets/icons/google.png
    - assets/icons/electronics.png
    - assets/icons/fashion.png
    - assets/icons/furniture.png
    - assets/icons/industrial.png
    - assets/icons/home_decor.png
    - assets/icons/construction.png
    - assets/icons/fabrication.png
    - assets/icons/electrical_equipment.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

 
  
